name: oasiscrop
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - gdal
  - numpy
  - pandas
  - opencv
  - tqdm
  - pyyaml
  - tifffile
  - pip
  - pip:
      - -e .
